# Generated by Django 3.2.18 on 2023-05-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='movie_id',
        ),
    ]
