# Generated by Django 3.2.18 on 2023-05-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
